# Generated by Django 5.2.2 on 2025-06-05 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoaSubmission',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('digital_signature', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('approved_applicant', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='public.approvedapplicant')),
            ],
        ),
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='public.application')),
                ('moa', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='scholar.moasubmission')),
                ('partner_org', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='account.partnerorganization')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('testimonial', models.TextField(blank=True, max_length=2000, null=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='job_media/')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scholar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholar.scholar')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('issuing_organization', models.CharField(max_length=255)),
                ('issue_month', models.PositiveSmallIntegerField()),
                ('issue_year', models.PositiveSmallIntegerField()),
                ('expiration_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('expiration_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=100, null=True)),
                ('credential_url', models.URLField(blank=True, max_length=500, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scholar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholar.scholar')),
            ],
        ),
    ]
