# Generated by Django 5.2.2 on 2025-06-05 07:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='moasubmission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=20, primary_key=True, serialize=False),
        ),
    ]
