# Generated by Django 5.2.2 on 2025-06-05 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('public', '0001_initial'),
        ('scholar', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationReview',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('action_reason', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='account.admin')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='public.application')),
            ],
        ),
        migrations.CreateModel(
            name='MoaReview',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('action_reason', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='account.admin')),
                ('moa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='scholar.moasubmission')),
            ],
        ),
    ]
