# Generated by Django 5.2.2 on 2025-06-05 07:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='password_hash',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='admin',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='admin',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='partner_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='admins', to='account.partnerorganization'),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
