# Generated by Django 5.2.2 on 2025-06-05 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('state_region_province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('education_status', models.CharField(choices=[('CURRENTLY_ENROLLED', 'Currently Enrolled'), ('FRESH_GRADUATE', 'Fresh Graduate'), ('GRADUATE', 'Graduate'), ('GAP_YEAR', 'Gap Year')], max_length=20)),
                ('institution_country', models.CharField(max_length=100)),
                ('institution_name', models.CharField(max_length=255)),
                ('programming_experience', models.CharField(choices=[('NONE', 'None'), ('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20)),
                ('data_science_experience', models.CharField(choices=[('NONE', 'None'), ('BASIC', 'Basic'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20)),
                ('weekly_time_commitment', models.CharField(choices=[('1-2', '1-2'), ('3-5', '3-5'), ('6-10', '6-10'), ('11-15', '11-15'), ('16+', '16+')], max_length=10)),
                ('scholarship_reason', models.TextField(max_length=1000)),
                ('career_goals', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('partner_org', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='account.partnerorganization')),
            ],
            options={
                'unique_together': {('email', 'partner_org')},
            },
        ),
        migrations.CreateModel(
            name='ApprovedApplicant',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='public.application')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationConnectivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectivity_type', models.CharField(choices=[('MOBILE_DATA', 'Mobile Data'), ('WIFI', 'WiFi')], max_length=20)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.application')),
            ],
            options={
                'unique_together': {('application', 'connectivity_type')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationDemographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demographic_group', models.CharField(choices=[('UNEMPLOYED', 'Unemployed'), ('UNDEREMPLOYED', 'Underemployed'), ('BELOW_POVERTY', 'Below Poverty'), ('REFUGEE', 'Refugee'), ('DISABLED', 'Disabled'), ('STUDENT', 'Student'), ('WORKING_STUDENT', 'Working Student'), ('NONPROFIT_SCIENTIST', 'Nonprofit Scientist')], max_length=30)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.application')),
            ],
            options={
                'unique_together': {('application', 'demographic_group')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('SMARTPHONE', 'Smartphone'), ('LAPTOP', 'Laptop'), ('DESKTOP', 'Desktop')], max_length=20)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.application')),
            ],
            options={
                'unique_together': {('application', 'device_type')},
            },
        ),
    ]
